version: "3.9"

services:
  scraper:
    build: ./scraper
    env_file:
      - .env
    volumes:
      - ./shared:/app/shared

  summarizer:
    build: ./summarizer
    depends_on:
      - scraper
    env_file:
      - .env
    volumes:
      - ./shared:/app/shared

#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     depends_on:
#       - summarizer
#     volumes:
#       - ./shared:/app/shared
